"""empty message

Revision ID: 8c6a203cc0ca
Revises: d8574e9585be
Create Date: 2022-10-19 14:26:00.698970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c6a203cc0ca'
down_revision = 'd8574e9585be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'user', ['name'], unique=False)
    # ### end Alembic commands ###
